project_id = "qohryjlwgpchrrglnmip"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.recolor-furniture]
verify_jwt = false

[functions.segment-furniture]
verify_jwt = false

[functions.place-in-background]
verify_jwt = false

[functions.suggest-colors]
verify_jwt = false

[functions.admin-chat]
verify_jwt = false
